docs_dir: docs/book
site_dir: docs/html
nav:
  - Home: index.md
  - Introduction: v1/intro.md
  - Installation: v1/installation.md
  - Quick Start: v1/quick-start.md
  - Middleware: v1/middleware.md
site_name: mezzio-cors
site_description: 'CORS component for Mezzio and other PSR-15 middleware runners.'
repo_url: 'https://github.com/mezzio/mezzio-cors'
extra:
    project: Mezzio
    installation:
      config_provider_class: 'Mezzio\Cors\ConfigProvider'
